### PR TITLE
Auto rotate carousel every 1 second

### LINKED ISSUE #11: Implement auto rotate feature on Partners Carousel
There is a carousel in our Partners section, We need to make it rotate automatically on a certain timeout. 

Look at it's documentation over [here](http://materializecss.com/carousel.html). And implement the necessary code to do it.

Feel free to ask questions in the comments and read the [contributing doc](https://github.com/fcckarachi/fcckarachi.github.io/blob/develop/CONTRIBUTING.md) before moving forward.

### PR DESCRIPTION
**Pull request by UsaidMuhammad**
Implemented auto-rotate feature by using the setInterval function every second. closes #11

### CODE REVIEW

**Comment by nawazishali** [comment]
@UsaidMuhammad Awesome! thanks for the contribution. 👍 If you are our [Facebook group](https://www.facebook.com/groups/free.code.camp.karachi) member don't forget to brag about your PR there.

**Comment by Abdul-Moiz-Ansari** [comment]
Great Contribution @UsaidMuhammad, but one second seems very fast. 2 or 2.5 seconds would be better.

**Comment by nawazishali** [comment]
@Abdul-Moiz-Ansari We will be opening another issue for it. having more issues for new comers is much better.

**Comment by Abdul-Moiz-Ansari** [comment]
Great...

**Pull request merged**
