### PR TITLE
Solved issue no 3:  SideNav left to right

### PR DESCRIPTION
**Pull request by afraz-afaq**
Fixed the issue #3 Re-position Menu & Menu button on right side.

### CODE REVIEW

**Comment by nawazishali** [comment]
Hey @afraz-afaq Thanks for making a PR, But this can't be merged due to following reasons.
1. Branch name is not according to the convention we are using, i.e fix/menu-issue
2. Style properties must be avoided as long as possible.
3. When the logo is menu icon is floated left you Logo must move a to the left corner.

Here are some possible solutions.

1. There are `.right` & `.left` classes already available in the library. Try using them.
2. Change the style for `brand-logo img` there is a margin-left of 35px on the logo image which is making it look bad on mobile screen.
3. Make another PR from proper branch name so that we can merge it.

Ask more questions if you need help.

**Comment by afraz-afaq** [comment]
@nawazishali thanks for your response I have used .right class but for brand-logo img to remove margin-left i must use style properties?

**Comment by nawazishali** [comment]
@afraz-afaq You can either add a class of your own or directly target img styles in css. If you have confusion with that part you can always ask for help.

**Comment by nawazishali** [comment]
@afraz-afaq If you are still working on the issue, Than please get it assigned to yourself by commented at the actual issue itself. Also join our organization [here](https://orgmanager.miguelpiedrafita.com/o/fcckarachi)

**Pull request closed without merging**
